#!/usr/bin/python

path = '/usr/src/gstreamer-phone'
import sys
if not path in sys.path:
	sys.path.append(path)

from subprocess import Popen
from shlex import split
from monitor import pidof

# ensure, only one instance is running
#p = pidof('gst-phone').strip().split(' ')
#if len(p) > 1:
#	Popen(split('kill '+' '.join(p[1:])))
#p = pidof('gstreamer-phone').strip().split(' ')
#if len(p) > 1:
#	Popen(split('kill '+' '.join(p[1:])))

# parallel task
Popen(split(path+'/monitor.py'))

if open('/etc/hostname').read().strip().lower() == 'pummeluff':
	import lohmann
else:
	import paintner

