#!/usr/bin/python

from sys import argv, exit

from ConfigParser import RawConfigParser

from subprocess import Popen, PIPE
from shlex import split

from log import *

#print "Updating ..."
#Popen(['git','pull']).wait()

config = RawConfigParser()
configfile = "/etc/gst-phone.conf"
try:
	config.read(configfile)
except:
	print "Error: "+configfile+" not found."
	exit()

# read config file
v4l2_ctl		= config.get('settings', 'v4l2-ctl')
gst_inspect	= config.get('settings', 'gst-inspect')
gst_launch	= config.get('settings', 'gst-launch')
retries		= int(config.get('settings', 'default_retries'))

# testing for Raspberry Pi OpenMAX libraries
if 'omxh264dec' in Popen(split(gst_inspect), stdout=PIPE).communicate()[0]:
	log("Good: gstreamer has OpenMAX superpowers!")
else:
	log("Warning: gstreamer does not appear to have OpenMAX powers.")

# webcam present ?
d = Popen(split(v4l2_ctl+' --list-devices'), stdout=PIPE, stderr=PIPE).communicate()[0].strip()
if len(d) > 0 and not 'Failed' in d:
	log(d)
else:
	log("No webcam ?")

if len(argv) > 1:
	# client mode
	log("Inviting "+argv[1]+" ...")
	from client import *
	sip = Client()
	sip.invite(argv[1], 5060)
	sip.wait(timeout=3000)

else:
	# server mode
	log("Noone to call. Waiting for incoming call. Press Ctrl+C to quit ...")
	from server import *
	s = Server()
	s.listen('192.168.2.121', 5060)
	s.wait(timeout=3000)
