#!/usr/bin/python

from sys import argv, exit
#from ConfigParser import RawConfigParser
from subprocess import Popen, PIPE
from shlex import split
from log import *

#print "Updating ..."
#Popen(['git','pull']).wait()

#config = RawConfigParser()
#configfile = "/etc/gst-phone.conf"
#try:
#	config.read(configfile)
#except:
#	print "Error: "+configfile+" not found."

# testing for Raspberry Pi OpenMAX libraries
if 'omxh264dec' in Popen(['gst-inspect-0.10'], stdout=PIPE).communicate()[0]:
	log("gstreamer has OpenMAX superpowers")
else:
	log("No hardware acceleration")

# testing for webcam
if 'Logitech' in Popen(split('v4l2-ctl --list-devices'), stdout=PIPE, stderr=PIPE).communicate()[0].strip():
	log("Logitech webcam")
else:
	log("No supported camera")

# choosing sink
if len(Popen(['pidof','X'], stdout=PIPE).communicate()[0].strip()) > 0:
	log('Xorg running, displaying on xvimagesink')
	sink = 'xvimagesink'
