#! /bin/sh
### BEGIN INIT INFO
# Provides:          gstreamer-phone
# Should-Start:      
# Required-Start:    networking ifplugd
# Required-Stop:     
# Default-Start:     2
# Default-Stop:      
# Short-Description: gstreamer-phone
# Description:       gstreamer-phone
### END INIT INFO

/usr/src/gstreamer-phone/cronscript.py
/usr/src/gstreamer-phone/gst-phone

