#! /bin/sh
### BEGIN INIT INFO
# Provides:          gstreamer-phone
# Should-Start:      
# Required-Start:    $local_fs networking ifplugd
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: gstreamer-phone
# Description:       gstreamer-phone
### END INIT INFO

/usr/src/gstreamer-phone/cronscript.py
/usr/src/gstreamer-phone/gst-phone

