#!/bin/bash

#
# $1: remote host to transfer video stream to
#

if [ "$1" == "" ]; then
	echo "Parameter missing: remote host to stream to"
	exit
	fi

if [ "$(pidof gst-launch-0.10)" != "" ]; then
	kill -s KILL $(pidof gst-launch-0.10)
	fi

# RTP/UDP
gst-launch-0.10 -q uvch264_src device=/dev/video0 name=src auto-start=true initial-bitrate=800000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=640,height=480,framerate=5/1' ! rtph264pay ! udpsink host=192.168.2.116 port=9070

# stdout
#gst-launch-0.10 -q uvch264_src device=/dev/video0 name=src auto-start=true initial-bitrate=400000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=1280,height=720,framerate=30/1' ! filesink location=/dev/stdout

