#!/bin/bash

gstreamer_phone="/usr/src/gstreamer-phone/streaming"
ssh -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$1 "$gstreamer_phone/paintner-to-lohmann pummeluff"

