#!/bin/bash

#
# $1: remote end to stream to
#
# This script starts capturing locally and
# starts playback on the remote end via SSH command
#

#method="RTP"
method="RTP"
port=9080

if [ "$1" == "" ]; then
	echo "Error: Remote address not specified"
	exit
	fi

gstreamer_phone="/usr/src/gstreamer-phone/streaming"

# establish SSH tunnel to communication endpoint
if [ "$method" == "SSH" ]; then
	killall ssh; sleep 1; ssh -v -o ConnectTimeout=5 -o StrictHostKeyChecking=no root@$1 -fNR $port:localhost:$port
	fi

# begin playback on the remote end
ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no root@$1 "$gstreamer_phone/play" &

# give the gstreamer on the remote end some time for startup
sleep 1

# begin capturing + streaming
if [ "$method" == "SSH" ]; then
	$gstreamer_phone/capture localhost
else
	$gstreamer_phone/capture "$1"
	fi

# terminate playback on remote end
ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no root@$1 "killall gst-launch-1.0" 

# close SSH tunnel
if [ "$method" == "SSH" ]; then
	killall ssh
	fi

