#!/bin/bash

gst-launch-0.10 -q uvch264_src device=/dev/video0 name=src auto-start=true initial-bitrate=360000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=800,height=600,framerate=5/1' ! filesink location=/dev/stdout | ssh root@pummeluff "gst-launch-1.0 -q filesrc location=/dev/stdin ! queue ! h264parse ! omxh264dec ! eglglessink"
