#!/bin/bash

# RTP
gst-launch-1.0 -v udpsrc port=9070 ! 'application/x-rtp,payload=96,encoding-name=H264' ! queue2 use-buffering=true low-percent=0 high-percent=100 ! rtph264depay ! h264parse ! omxh264dec ! eglglessink

# TCP
#gst-launch-1.0 -v --gst-debug=eglgles:5 tcpclientsrc host=bonesaw port=9078 ! 'video/x-h264' ! h264parse ! omxh264dec ! autovideosink

# file
#gst-launch-1.0 -v filesrc location=src/c920.h264 ! h264parse ! omxh264dec ! autovideosink

# stdin
#gst-launch-1.0 -v filesrc location=/dev/stdin ! h264parse ! queue2 use-buffering=true ! omxh264dec ! fakesink #eglglessink

