#!/bin/bash

# V4L2
#gst-launch-0.10 -v v4l2src device=/dev/video1 ! 'video/x-h264,width=800' ! rtph264pay ! udpsink host=pikachu port=9078 sync=false

# RTP/UDP
#gst-launch-0.10 -q uvch264_src device=/dev/video0 name=src auto-start=true initial-bitrate=400000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=800,height=600,framerate=5/1' ! rtph264pay ! udpsink host=pummeluff.local port=9070

# TCP
#gst-launch-0.10 -v uvch264_src device=/dev/video1 name=src auto-start=true initial-bitrate=360000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=1280,height=720,framerate=5/1' ! tcpserversink host=pikachu port=9078

# file; 360
#gst-launch-0.10 -v uvch264_src device=/dev/video1 name=src auto-start=true initial-bitrate=360000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=1280,height=720,framerate=5/1' ! filesink location=/media/Pikachu/usr/src/c920.h264
#rtph264pay ! udpsink host=pikachu port=9078

# stdout
gst-launch-0.10 -q uvch264_src device=/dev/video0 name=src auto-start=true initial-bitrate=320000 src.vfsrc ! queue ! 'video/x-raw-yuv,width=320,height=240' ! fakesink . src.vidsrc ! queue ! 'video/x-h264,width=1280,height=720,framerate=5/1' ! filesink location=/dev/stdout

